/*
Monthly acquisition-context analysis.
"Acquisition-month" means revenue generated by a customer during the calendar
month of their first order. It is not the same as first-order revenue.
*/
WITH classified AS (
    SELECT
        DATE_TRUNC('month', orderdate)::date AS month,
        customerkey,
        order_revenue_usd,
        CASE
            WHEN DATE_TRUNC('month', orderdate) = DATE_TRUNC('month', first_purchase_date)
                THEN 'Acquisition-Month'
            ELSE 'Returning'
        END AS customer_type
    FROM fact_orders
)
SELECT
    month,
    COUNT(DISTINCT CASE WHEN customer_type = 'Acquisition-Month' THEN customerkey END)
        AS acquisition_month_customers,
    COUNT(DISTINCT CASE WHEN customer_type = 'Returning' THEN customerkey END)
        AS returning_customers,
    COUNT(DISTINCT customerkey) AS total_customers,
    ROUND(
        COUNT(DISTINCT CASE WHEN customer_type = 'Returning' THEN customerkey END) * 100.0
        / NULLIF(COUNT(DISTINCT customerkey), 0),
        1
    ) AS returning_customer_pct,
    ROUND(SUM(CASE WHEN customer_type = 'Acquisition-Month' THEN order_revenue_usd ELSE 0 END)::numeric, 0)
        AS acquisition_month_revenue_usd,
    ROUND(SUM(CASE WHEN customer_type = 'Returning' THEN order_revenue_usd ELSE 0 END)::numeric, 0)
        AS returning_customer_revenue_usd,
    ROUND(SUM(order_revenue_usd)::numeric, 0) AS total_revenue_usd
FROM classified
GROUP BY month
ORDER BY month;
